### ISSUE TITLE
Bug: Sometimes SUMMARY.md not regenerated

### ISSUE THREAD

**Issue by brycefisher** [knightflower1989/mdbook-auto-gen-summary#2]
Steps to reproduce:
 1. `mdbook-auto-gen-summary gen path/to/src`
 2. `rm path/to/src/SUMMARY.md`
 3. `mdbook-auto-gen-summary gen path/to/src`

Expected result:
 - The SUMMARY.md file should be re-generated

Actual result:
 - The SUMMARY.md file on disk remains unchanged.

----

Proposed solution: compare md5 of existing SUMMARY.md **disk** to md5 of in-memory SUMMARY.md. Don't create temp file at all.

Alternative solution: allow an envvar or argument to disable cache and always regenerate SUMMARY.md regardless of md5.

**Comment by cococolanosugar** [comment]
bugfixed
