### ISSUE TITLE
Feature: Parse first h1 of markdown text to generate link text for SUMMARY.md

### ISSUE THREAD

**Issue by brycefisher** [knightflower1989/mdbook-auto-gen-summary#3]
## How it is now:

 - Filenames are stripped of .md and used as link text in SUMMARY. Ex: foo.md -> `[foo](./foo.html)`
 - The markdown parser in mdbook cannot parse links that contain spaces. Ex: "Everything Foo Bar.md" -> `[Everything Foo Bar](./Everything Foo Bar.html)` -> mdbook fails to build

## Problem

Often the filename is not what I want to show to the readers.

## Insight

Usually, the first line of the markdown contains the title I want to appear in SUMMARY.md

## Proposal

Have mdbook-auto-gen-summary parse the markdown content for the 1st line (or the 1st heading), use that as the link text for the item in SUMMARY.md

---

I'd be willing to contribute this feature, if @knightflower1989 is willing to accept well written code for this.

There's probably many other ways to achieve the desired outcome here. Let me know if you would rather pursue a different direction.

**Comment by cococolanosugar** [comment]
Any optimizations that help with this pluging are welcome.
I am glad if you can share your code!

**Comment by brycefisher** [comment]
Ok! Great. I'll work on a PR. Thanks!!
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cococolanosugar** [comment]
Use -t to make 1st h1 line as  link text.

If no h1 line，file name as default link text.
